language: android
before_install:
    - android list sdk --no-ui --all --extended
android:
    components:
        - tools
        - build-tools-23.0.2
        - android-23
        - extra-google-google_play_services
        - add-on
        - extra
